import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./burger.css";
import Link from "next/link";
import Image from "next/image";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="px-[20px] w-[100%] z-[999] h-[50px] fixed bg-[#FFFAF0] pt-[5px] flex justify-between items-center border-b-[1px] opacity-[0.9] shadow-md">
          <Link href="/">This is Okinawa</Link>
          <div className="menu-btn-new">
            <div className="burger-top">
              <div className="burger-icon burger-icon-top"></div>
            </div>
          </div>
        </div>
        <div className="relative pt-[50px]">
          {children}
        </div>
      </body>
    </html>
  );
}
